version: "3"
services:
  app:
    # 起動イメージ
    image: node:16-alpine
    # nodeサーバーなのでこのように命名
    container_name: ssr-sample-app
    # 環境変数
    environment:
      - NODE_ENV=development
    tty: true
    # ホスト側のポート：コンテナのポート
    ports:
      - "3000:3000"
    # ホスト側のsrcをコンテナのappにマウント
    volumes:
      - ./:/app
    # 起動時のカレントフォルダ
    working_dir: /app
    # 起動後に実行するコマンド
    command: yarn start
    # dbを読む
    depends_on:
      - db
  db:
    platform: linux/x86_64
    image: mysql:8.0
    # nodeサーバーなのでこのように命名
    container_name: ssr-sample-db
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - ${DB_PORT}:3306
volumes:
  db-store:
